DEFINES=NDEBUG

EXTRA_INCLUDES=
EXTRA_SRCDIR=
	
ifneq ($(MAKE_FLAGS),)
 	ifeq ($(findstring CONFIG_USB_HOST_MSC,$(MAKE_FLAGS)), CONFIG_USB_HOST_MSC)	
  	EXTRA_SRCDIR+=src/gd32/usb
 	endif
else
  	EXTRA_SRCDIR+=src/gd32/usb
endif

include Rules.mk
include ../firmware-template-gd32/lib/Rules.mk
